#!/bin/bash
#SBATCH -c 10
#SBATCH --mem=100G

/home/namk/work_faw_adaptation/programs/kmerfreq-master/kmerfreq -k 17 -t 10 -p /home/namk/work_faw_adaptation/Kiwoong/Projects/sfrugi_PseudoPangenomics/CGE/kmerfreq/FP100000482BL_L01_544 /home/namk/work_faw_adaptation/Kiwoong/Projects/sfrugi_PseudoPangenomics/CGE/lib/FP100000482BL_L01_544.lib

