#!/bin/bash
#SBATCH -c 10
#SBATCH --mem=100G

cd /home/namk/work_faw_adaptation/Kiwoong/Projects/sfrugi_PseudoPangenomics/Zhang/jellyfish

zcat /home/namk/work_faw_adaptation/processing_fq/Zhang_PRJNA591441_n228/SRR20748753* | grep -v + | grep -v @ | wc -l > SRR20748753.wc
zcat /home/namk/work_faw_adaptation/processing_fq/Zhang_PRJNA591441_n228/SRR20748753* | /home/namk/work_faw_adaptation/programs/jellyfish-2.3.1/bin/jellyfish count /dev/fd/0 -C -m 17 -s 500000000 -t 10  -o /dev/stdout | /home/namk/work_faw_adaptation/programs/jellyfish-2.3.1/bin/jellyfish histo /dev/fd/0 -t 10 > SRR20748753.histo
